development:
  adapter: postgresql
  database: da30ki989uli2
  host: ec2-107-22-251-225.compute-1.amazonaws.com
  port: 5432
  username: ucfxnxntwseqxi
  password: IFzG1P8R9hf5VS4UFz8lkqN_nG
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: da30ki989uli2
  host: ec2-107-22-251-225.compute-1.amazonaws.com
  port: 5432
  username: ucfxnxntwseqxi
  password: IFzG1P8R9hf5VS4UFz8lkqN_nG
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: da30ki989uli2
  host: ec2-107-22-251-225.compute-1.amazonaws.com
  port: 5432
  username: ucfxnxntwseqxi
  password: IFzG1P8R9hf5VS4UFz8lkqN_nG
  pool: 5
  timeout: 5000
